# fly.toml app configuration file generated for api-multiclicker on 2025-05-15T13:49:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-multiclicker'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  idle_timeout = 3600 

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
